// Test de los Cinco Grandes (Big Five / OCEAN)
// 120 preguntas validadas en español
// Fuente: bigfive-web (rubynor) — IPIP-NEO-PI

export interface BigFiveQuestion {
  text: string
  keyed: 'plus' | 'minus'
  domain: string
  facet: number
}

export const BIGFIVE_QUESTIONS: BigFiveQuestion[] = [
  { text: 'Me preocupo por las cosas', keyed: 'plus', domain: 'N', facet: 1 },
  { text: 'Creo que hago amigos fácilmente', keyed: 'plus', domain: 'E', facet: 1 },
  { text: 'Tengo una imaginación vívida', keyed: 'plus', domain: 'O', facet: 1 },
  { text: 'Confío en los demás', keyed: 'plus', domain: 'A', facet: 1 },
  { text: 'Completo las tareas correctamente', keyed: 'plus', domain: 'C', facet: 1 },
  { text: 'Suelo enojarme fácilmente', keyed: 'plus', domain: 'N', facet: 2 },
  { text: 'Me encantan las fiestas grandes', keyed: 'plus', domain: 'E', facet: 2 },
  { text: 'Creo que el arte es importante', keyed: 'plus', domain: 'O', facet: 2 },
  { text: 'Colaboro con otros solo si obtengo algún beneficio propio', keyed: 'minus', domain: 'A', facet: 2 },
  { text: 'Me gusta mantener las cosas en orden', keyed: 'plus', domain: 'C', facet: 2 },
  { text: 'A menudo me siento triste', keyed: 'plus', domain: 'N', facet: 3 },
  { text: 'Me gusta estar a cargo de las decisiones', keyed: 'plus', domain: 'E', facet: 3 },
  { text: 'Considero que soy muy sentimental', keyed: 'plus', domain: 'O', facet: 3 },
  { text: 'Me siento a gusto ayudando a los demás', keyed: 'plus', domain: 'A', facet: 3 },
  { text: 'Siempre cumplo mis promesas', keyed: 'plus', domain: 'C', facet: 3 },
  { text: 'Tengo dificultades para acercarme a los demás', keyed: 'plus', domain: 'N', facet: 4 },
  { text: 'Estoy ocupado/a todo el tiempo', keyed: 'plus', domain: 'E', facet: 4 },
  { text: 'Prefiero la variedad antes que la rutina', keyed: 'plus', domain: 'O', facet: 4 },
  { text: 'Me gusta pelear', keyed: 'minus', domain: 'A', facet: 4 },
  { text: 'Siempre trabajo duro', keyed: 'plus', domain: 'C', facet: 4 },
  { text: 'A menudo voy de borracheras', keyed: 'plus', domain: 'N', facet: 5 },
  { text: 'Amo la emoción', keyed: 'plus', domain: 'E', facet: 5 },
  { text: 'Me gusta mucho leer', keyed: 'plus', domain: 'O', facet: 5 },
  { text: 'Creo que soy mejor que los demás', keyed: 'minus', domain: 'A', facet: 5 },
  { text: 'Siempre estoy preparado', keyed: 'plus', domain: 'C', facet: 5 },
  { text: 'Me asusto fácilmente', keyed: 'plus', domain: 'N', facet: 6 },
  { text: 'Soy una persona muy alegre', keyed: 'plus', domain: 'E', facet: 6 },
  { text: 'Tiendo a votar por candidatos políticos liberales', keyed: 'plus', domain: 'O', facet: 6 },
  { text: 'Me compadezco por la gente sin hogar', keyed: 'plus', domain: 'A', facet: 6 },
  { text: 'Hago las cosas sin razonar mucho sobre ellas', keyed: 'minus', domain: 'C', facet: 6 },
  { text: 'Temo que suceda lo peor', keyed: 'plus', domain: 'N', facet: 1 },
  { text: 'Me siento cómodo con la gente', keyed: 'plus', domain: 'E', facet: 1 },
  { text: 'Disfruto de fantásticos vuelos de fantasía', keyed: 'plus', domain: 'O', facet: 1 },
  { text: 'Creo que las personas tienen buenas intenciones', keyed: 'plus', domain: 'A', facet: 1 },
  { text: 'Soy muy bueno en lo que hago', keyed: 'plus', domain: 'C', facet: 1 },
  { text: 'Me suelo molestar con facilidad', keyed: 'plus', domain: 'N', facet: 2 },
  { text: 'Me gusta hablar con muchas personas en las fiestas', keyed: 'plus', domain: 'E', facet: 2 },
  { text: 'Veo belleza en cosas que otros podrían no notar', keyed: 'plus', domain: 'O', facet: 2 },
  { text: 'Podría hacer trampa si eso me lleva adelante', keyed: 'minus', domain: 'A', facet: 2 },
  { text: 'A menudo olvido poner las cosas de vuelta donde las tomé', keyed: 'minus', domain: 'C', facet: 2 },
  { text: 'No me siento bien conmigo mismo', keyed: 'plus', domain: 'N', facet: 3 },
  { text: 'Intento dirigir a los demás', keyed: 'plus', domain: 'E', facet: 3 },
  { text: 'Puedo comprender bien las emociones de los demás', keyed: 'plus', domain: 'O', facet: 3 },
  { text: 'Me preocupo por los demás', keyed: 'plus', domain: 'A', facet: 3 },
  { text: 'Siempre digo la verdad', keyed: 'plus', domain: 'C', facet: 3 },
  { text: 'Temo ser el centro de atención', keyed: 'plus', domain: 'N', facet: 4 },
  { text: 'Creo que soy una persona activa y vigorosa', keyed: 'plus', domain: 'E', facet: 4 },
  { text: 'Prefiero quedarme cosas que conozco', keyed: 'minus', domain: 'O', facet: 4 },
  { text: 'Suelo gritar a las personas', keyed: 'minus', domain: 'A', facet: 4 },
  { text: 'Hago más de lo que se espera de mí', keyed: 'plus', domain: 'C', facet: 4 },
  { text: 'Rara vez me dejo llevar', keyed: 'minus', domain: 'N', facet: 5 },
  { text: 'Siempre busco la aventura', keyed: 'plus', domain: 'E', facet: 5 },
  { text: 'Intento evitar discusiones filosóficas', keyed: 'minus', domain: 'O', facet: 5 },
  { text: 'Espero mucho de mí mismo', keyed: 'minus', domain: 'A', facet: 5 },
  { text: 'Llevo a cabo mis planes', keyed: 'plus', domain: 'C', facet: 5 },
  { text: 'Me abrumo fácilmente de las cosas que suceden alrededor', keyed: 'plus', domain: 'N', facet: 6 },
  { text: 'Pienso que soy una persona muy divertida', keyed: 'plus', domain: 'E', facet: 6 },
  { text: 'No creo que haya acciones completamente correctas o incorrectas', keyed: 'plus', domain: 'O', facet: 6 },
  { text: 'Siento simpatía por aquellos que se encuentran en peores situaciones que yo', keyed: 'plus', domain: 'A', facet: 6 },
  { text: 'Suelo tomar decisiones precipitadas', keyed: 'minus', domain: 'C', facet: 6 },
  { text: 'Tengo miedo de muchas cosas', keyed: 'plus', domain: 'N', facet: 1 },
  { text: 'A menudo evito el contacto con los demás', keyed: 'minus', domain: 'E', facet: 1 },
  { text: 'Soy una persona que a veces sueña despierta', keyed: 'plus', domain: 'O', facet: 1 },
  { text: 'Confío en lo que dicen las personas', keyed: 'plus', domain: 'A', facet: 1 },
  { text: 'Realizo mis tareas sin ningún problema', keyed: 'plus', domain: 'C', facet: 1 },
  { text: 'A veces pierdo los estribos', keyed: 'plus', domain: 'N', facet: 2 },
  { text: 'Prefiero estar solo', keyed: 'minus', domain: 'E', facet: 2 },
  { text: 'No me gusta la poesía', keyed: 'minus', domain: 'O', facet: 2 },
  { text: 'Me aprovecho de los demás', keyed: 'minus', domain: 'A', facet: 2 },
  { text: 'Mi habitación es muy desordenada', keyed: 'minus', domain: 'C', facet: 2 },
  { text: 'A menudo me siento bajoneado', keyed: 'plus', domain: 'N', facet: 3 },
  { text: 'Tomo el control de las cosas', keyed: 'plus', domain: 'E', facet: 3 },
  { text: 'En raras ocasiones noto mis reacciones emocionales', keyed: 'minus', domain: 'O', facet: 3 },
  { text: 'Soy indiferente a los sentimientos de los demás', keyed: 'minus', domain: 'A', facet: 3 },
  { text: 'Las reglas fueron hechas para romperse', keyed: 'minus', domain: 'C', facet: 3 },
  { text: 'Sólo me siento cómodo en compañía de amigos', keyed: 'plus', domain: 'N', facet: 4 },
  { text: 'Hago muchas cosas en mi tiempo libre', keyed: 'plus', domain: 'E', facet: 4 },
  { text: 'No me atraen situaciones en constante cambio', keyed: 'minus', domain: 'O', facet: 4 },
  { text: 'No tengo recelo en insultar a la gente', keyed: 'minus', domain: 'A', facet: 4 },
  { text: 'Solo hago el trabajo justo para haberlo cumplido', keyed: 'minus', domain: 'C', facet: 4 },
  { text: 'Resisto las tentaciones fácilmente', keyed: 'minus', domain: 'N', facet: 5 },
  { text: 'Me gusta ser imprudente', keyed: 'plus', domain: 'E', facet: 5 },
  { text: 'Me es difícil entender ideas abstractas', keyed: 'minus', domain: 'O', facet: 5 },
  { text: 'Tengo altas expectativas de mí mismo', keyed: 'minus', domain: 'A', facet: 5 },
  { text: 'No hago mucho en mi tiempo libre', keyed: 'minus', domain: 'C', facet: 5 },
  { text: 'A veces siento que no soy capaz de manejar situaciones', keyed: 'plus', domain: 'N', facet: 6 },
  { text: 'Amo la vida', keyed: 'plus', domain: 'E', facet: 6 },
  { text: 'Tiendo a votar por los candidatos políticos conservativos', keyed: 'minus', domain: 'O', facet: 6 },
  { text: 'No me suelo implicar en los problemas de los demás', keyed: 'minus', domain: 'A', facet: 6 },
  { text: 'Hago las cosas sin cautela', keyed: 'minus', domain: 'C', facet: 6 },
  { text: 'Tiendo a estresarme con facilidad', keyed: 'plus', domain: 'N', facet: 1 },
  { text: 'Siempre mantengo cierta distancia con las personas', keyed: 'minus', domain: 'E', facet: 1 },
  { text: 'Me gusta perderme en mis pensamientos', keyed: 'plus', domain: 'O', facet: 1 },
  { text: 'Desconfío de la gente', keyed: 'minus', domain: 'A', facet: 1 },
  { text: 'Generalmente sé cómo hacer las cosas', keyed: 'plus', domain: 'C', facet: 1 },
  { text: 'No me molesto fácilmente', keyed: 'minus', domain: 'N', facet: 2 },
  { text: 'No me gusta mezclarme con la gente', keyed: 'minus', domain: 'E', facet: 2 },
  { text: 'No me agrada ir a museos de arte', keyed: 'minus', domain: 'O', facet: 2 },
  { text: 'Sería capaz de sabotear los planes de otros', keyed: 'minus', domain: 'A', facet: 2 },
  { text: 'Dejo mis pertenencias aquí y allá', keyed: 'minus', domain: 'C', facet: 2 },
  { text: 'Me siento cómodo conmigo mismo', keyed: 'minus', domain: 'N', facet: 3 },
  { text: 'Espero que alguien más lleve la batuta en un grupo', keyed: 'minus', domain: 'E', facet: 3 },
  { text: 'No comprendo a las personas que se emocionan fácilmente', keyed: 'minus', domain: 'O', facet: 3 },
  { text: 'No tengo tiempo para los demás', keyed: 'minus', domain: 'A', facet: 3 },
  { text: 'No suelo cumplir mis promesas', keyed: 'minus', domain: 'C', facet: 3 },
  { text: 'No me molestan las situaciones sociales difíciles', keyed: 'minus', domain: 'N', facet: 4 },
  { text: 'Me gusta tomar las cosas con calma', keyed: 'minus', domain: 'E', facet: 4 },
  { text: 'Soy una persona mayormente conservadora', keyed: 'minus', domain: 'O', facet: 4 },
  { text: 'No suelo apoyar a los otros', keyed: 'minus', domain: 'A', facet: 4 },
  { text: 'Pongo poco tiempo y esfuerzo en mi trabajo', keyed: 'minus', domain: 'C', facet: 4 },
  { text: 'Siempre puedo controlar mis antojos', keyed: 'minus', domain: 'N', facet: 5 },
  { text: 'Creo que soy una persona activa y vigorosa', keyed: 'plus', domain: 'E', facet: 5 },
  { text: 'No me interesan las discusiones teóricas', keyed: 'minus', domain: 'O', facet: 5 },
  { text: 'Me jacto de mis virtudes', keyed: 'minus', domain: 'A', facet: 5 },
  { text: 'Tengo dificultad para comenzar tareas', keyed: 'minus', domain: 'C', facet: 5 },
  { text: 'Me mantengo tranquilo/a bajo presión', keyed: 'minus', domain: 'N', facet: 6 },
  { text: 'Siempre miro el buen lado de la vida', keyed: 'plus', domain: 'E', facet: 6 },
  { text: 'Creo que deberíamos ser severos con el crimen', keyed: 'minus', domain: 'O', facet: 6 },
  { text: 'Trato de no pensar en los necesitados', keyed: 'minus', domain: 'A', facet: 6 },
  { text: 'Actúo sin pensar', keyed: 'minus', domain: 'C', facet: 6 },
]

// Dominios del Big Five
export const DOMAINS = {
  O: { name: 'Apertura', desc: 'Curiosidad intelectual, creatividad, apertura a nuevas experiencias' },
  C: { name: 'Responsabilidad', desc: 'Organización, autodisciplina, orientación a logros' },
  E: { name: 'Extraversión', desc: 'Sociabilidad, asertividad, búsqueda de estimulación' },
  A: { name: 'Amabilidad', desc: 'Cooperación, empatía, confianza en los demás' },
  N: { name: 'Neuroticismo', desc: 'Susceptibilidad al estrés, ansiedad, inestabilidad emocional' },
}

// Opciones de respuesta (escala Likert 5 puntos)
export const CHOICES = [
  { text: 'Muy en desacuerdo', score: 1 },
  { text: 'Moderadamente en desacuerdo', score: 2 },
  { text: 'Ni de acuerdo, ni en desacuerdo', score: 3 },
  { text: 'Moderadamente de acuerdo', score: 4 },
  { text: 'Muy de acuerdo', score: 5 },
]
