// Datos completos del Eneagrama — basado en Riso-Hudson (RHETI)
// Fuente: rheti.nthmost.com

export interface EnneagramType {
  id: number
  title: string
  name: string
  center: string
  centerDesc: string
  overview: string
  coreFear: string
  coreDesire: string
  stress: { type: number; name: string }
  growth: { type: number; name: string }
  wings: { code: string; name: string }[]
  famous: string[]
  strengths: string[]
  challenges: string[]
}

export const TYPES_FULL: EnneagramType[] = [
  {
    id: 1,
    title: 'Tipo 1',
    name: 'Individualista',
    center: 'Instintivo',
    centerDesc: 'These types lead with gut instinct and tend to relate to the world through action, autonomy, and control. Their core emotional issue is anger or rage.',
    overview: 'Ones are principled, purposeful, and self-disciplined — driven by a deep desire to be good and to improve the world around them. They have a strong inner critic that holds them to high standards, making them reliable, thorough, and fair. At their best, Ones are wise, discerning, and inspiring — acce',
    coreFear: 'Ser malo/a, defectuoso/a',
    coreDesire: 'Ser bueno/a, íntegro/a',
    stress: { type: 4, name: 'El Individualista' },
    growth: { type: 7, name: 'El Entusiasta' },
    wings: [{'code': '1w9', 'name': 'The Idealist'}, {'code': '1w2', 'name': 'The Advocate'}],
    famous: ['Mahatma Gandhi', 'Nelson Mandela', 'Hillary Clinton'],
    strengths: ['Integridad moral', 'Mejora continua', 'Responsabilidad', 'Visión clara'],
    challenges: ['Autocrítica', 'Rigidez', 'Juicio', 'Perfeccionismo'],
  },
  {
    id: 2,
    title: 'Tipo 2',
    name: 'Desafiador',
    center: 'Emocional',
    centerDesc: 'These types lead with emotion and tend to orient around image, identity, and connection. Their core emotional issue is shame.',
    overview: 'Twos are warm, caring, and interpersonally attuned — motivated by a genuine desire to be loved and to feel needed by others. They are often the first to sense what people around them need and to offer support, sometimes before being asked. At their best, Twos are unconditionally loving, generous, an',
    coreFear: 'No ser amado/a',
    coreDesire: 'Sentirse amado/a y apreciado',
    stress: { type: 8, name: 'El Desafiador' },
    growth: { type: 4, name: 'El Individualista' },
    wings: [{'code': '2w1', 'name': 'The Servant'}, {'code': '2w3', 'name': 'The Host'}],
    famous: ['Desmond Tutu', 'Mother Teresa', 'Dolly Parton'],
    strengths: ['Empatía profunda', 'Generosidad', 'Conexión humana', 'Apoyo incondicional'],
    challenges: ['Descuido propio', 'Necesidad de aprobación', 'Orgullo', 'Dependencia'],
  },
  {
    id: 3,
    title: 'Tipo 3',
    name: 'Pacificador',
    center: 'Emocional',
    centerDesc: 'These types lead with emotion and tend to orient around image, identity, and connection. Their core emotional issue is shame.',
    overview: 'Threes are ambitious, adaptable, and image-conscious — oriented toward achievement and the recognition that comes with it. They excel at reading what success looks like in any environment and shaping themselves accordingly. At their best, Threes are authentic, inspiring leaders who motivate others t',
    coreFear: 'No tener valor, ser insignificante',
    coreDesire: 'Sentirse valioso/a y digno/a',
    stress: { type: 9, name: 'El Pacificador' },
    growth: { type: 6, name: 'El Leal' },
    wings: [{'code': '3w2', 'name': 'The Charmer'}, {'code': '3w4', 'name': 'The Professional'}],
    famous: ['Oprah Winfrey', 'Tony Robbins', 'Muhammad Ali'],
    strengths: ['Determinación', 'Capacidad de inspirar', 'Adaptabilidad', 'Excelencia'],
    challenges: ['Imagen excesiva', 'Temor al fracaso', 'Competitividad', 'Desconexión'],
  },
  {
    id: 4,
    title: 'Tipo 4',
    name: 'Ayudador',
    center: 'Emocional',
    centerDesc: 'These types lead with emotion and tend to orient around image, identity, and connection. Their core emotional issue is shame.',
    overview: 'Fours are expressive, sensitive, and deeply in touch with their inner emotional world. They long to understand themselves and to be understood — to find meaning and authenticity in their lives. Creative and empathic, they often feel a sense of longing or of something essential being missing. At thei',
    coreFear: 'No tener identidad personal',
    coreDesire: 'Encontrar su identidad y significado',
    stress: { type: 2, name: 'El Ayudador' },
    growth: { type: 1, name: 'El Reformador' },
    wings: [{'code': '4w3', 'name': 'The Aristocrat'}, {'code': '4w5', 'name': 'The Bohemian'}],
    famous: ['Frida Kahlo', 'Bob Dylan', 'Billie Eilish'],
    strengths: ['Creatividad', 'Profundidad emocional', 'Autenticidad', 'Empatía'],
    challenges: ['Melancolía', 'Autoabsorción', 'Envidia', 'Inestabilidad'],
  },
  {
    id: 5,
    title: 'Tipo 5',
    name: 'Entusiasta',
    center: 'Mental',
    centerDesc: 'These types lead with analysis and tend to orient around safety, planning, and mental frameworks. Their core emotional issue is fear or anxiety.',
    overview: 'Fives are perceptive, analytical, and intensely private — motivated by the desire to understand the world deeply and to conserve their inner resources. They tend to observe more than participate, preferring to master a subject fully before engaging. At their best, Fives are visionary, open-minded, a',
    coreFear: 'Ser inútil, incompetente',
    coreDesire: 'Ser capaz y competente',
    stress: { type: 7, name: 'El Entusiasta' },
    growth: { type: 8, name: 'El Desafiador' },
    wings: [{'code': '5w4', 'name': 'The Iconoclast'}, {'code': '5w6', 'name': 'The Problem Solver'}],
    famous: ['Albert Einstein', 'Stephen Hawking', 'Tim Burton'],
    strengths: ['Analítico', 'Visionario', 'Independiente', 'Profundidad'],
    challenges: ['Aislamiento', 'Distanciamiento', 'Minimalismo', 'Evitación'],
  },
  {
    id: 6,
    title: 'Tipo 6',
    name: 'Triunfador',
    center: 'Mental',
    centerDesc: 'These types lead with analysis and tend to orient around safety, planning, and mental frameworks. Their core emotional issue is fear or anxiety.',
    overview: 'Sixes are responsible, committed, and security-oriented — attuned to risk and to the trustworthiness of people and institutions around them. They are loyal to those they trust and hardworking within systems they believe in. At their best, Sixes are courageous, reliable, and deeply devoted — finding ',
    coreFear: 'No tener guía ni apoyo',
    coreDesire: 'Tener seguridad y apoyo',
    stress: { type: 3, name: 'El Triunfador' },
    growth: { type: 9, name: 'El Pacificador' },
    wings: [{'code': '6w5', 'name': 'The Defender'}, {'code': '6w7', 'name': 'The Buddy'}],
    famous: ['Tom Hanks', 'Ellen DeGeneres', 'Sigmund Freud'],
    strengths: ['Lealtad', 'Responsabilidad', 'Coraje', 'Confianza'],
    challenges: ['Ansiedad', 'Desconfianza', 'Duda', 'Rebeldía'],
  },
  {
    id: 7,
    title: 'Tipo 7',
    name: 'Reformador',
    center: 'Mental',
    centerDesc: 'These types lead with analysis and tend to orient around safety, planning, and mental frameworks. Their core emotional issue is fear or anxiety.',
    overview: 'Sevens are enthusiastic, spontaneous, and future-oriented — propelled by a desire for new experiences, ideas, and possibilities. They bring energy and optimism to almost everything they do, and can synthesize diverse ideas with remarkable creativity. At their best, Sevens are joyful, accomplished, a',
    coreFear: 'Estar en dolor o privación',
    coreDesire: 'Ser feliz y satisfecho',
    stress: { type: 1, name: 'El Reformador' },
    growth: { type: 5, name: 'El Investigador' },
    wings: [{'code': '7w6', 'name': 'The Entertainer'}, {'code': '7w8', 'name': 'The Realist'}],
    famous: ['Robin Williams', 'Elton John', 'Amelia Earhart'],
    strengths: ['Optimismo', 'Versatilidad', 'Creatividad', 'Energía'],
    challenges: ['Dispersión', 'Evitación del dolor', 'Superficialidad', 'Impulsividad'],
  },
  {
    id: 8,
    title: 'Tipo 8',
    name: 'Investigador',
    center: 'Instintivo',
    centerDesc: 'These types lead with gut instinct and tend to relate to the world through action, autonomy, and control. Their core emotional issue is anger or rage.',
    overview: 'Eights are powerful, self-confident, and direct — motivated by a need to be in control of their own lives and to resist any form of weakness or domination. They engage the world with intensity and decisiveness, often naturally taking charge of situations. At their best, Eights are magnanimous, heroi',
    coreFear: 'Ser controlado o herido',
    coreDesire: 'Protegerse a sí mismo y a otros',
    stress: { type: 5, name: 'El Investigador' },
    growth: { type: 2, name: 'El Ayudador' },
    wings: [{'code': '8w7', 'name': 'The Maverick'}, {'code': '8w9', 'name': 'The Bear'}],
    famous: ['Winston Churchill', 'Serena Williams', 'Martin Luther King Jr.'],
    strengths: ['Liderazgo', 'Determinación', 'Protección', 'Directo'],
    challenges: ['Dominación', 'Confrontación', 'Intimidación', 'Vulnerabilidad'],
  },
  {
    id: 9,
    title: 'Tipo 9',
    name: 'Leal',
    center: 'Instintivo',
    centerDesc: 'These types lead with gut instinct and tend to relate to the world through action, autonomy, and control. Their core emotional issue is anger or rage.',
    overview: 'Nines are receptive, easygoing, and peace-seeking — motivated by a deep desire for harmony and a reluctance to assert themselves in ways that might cause conflict. They have a remarkable ability to see all sides of a situation and to make others feel heard and accepted. At their best, Nines are deep',
    coreFear: 'Pérdida y separación',
    coreDesire: 'Paz interior y totalidad',
    stress: { type: 6, name: 'El Leal' },
    growth: { type: 3, name: 'El Triunfador' },
    wings: [{'code': '9w8', 'name': 'The Referee'}, {'code': '9w1', 'name': 'The Dreamer'}],
    famous: ['Barack Obama', 'Carl Jung', 'Fred Rogers'],
    strengths: ['Armonía', 'Estabilidad', 'Empatía', 'Mediación'],
    challenges: ['Complacencia', 'Evitación del conflicto', 'Pasividad', 'Indecisión'],
  },
]
