'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'

/* ─────── ALL 9 ENNEAGRAM TYPES ─────── */
export const TYPES = [
  {
    id: 1,
    emoji: '😤',
    title: 'El Perfeccionista',
    name: 'El Reformador',
    desc: 'Riguroso, ético y con un fuerte sentido del bien y del mal. Busca mejorar todo lo que toca y teme ser defectuoso o equivocarse. Su don es la sabiduría y la integridad cuando logra aceptar la imperfección como parte de la vida.',
    strengths: ['Integridad moral', 'Capacidad de mejora continua', 'Sentido de responsabilidad', 'Visión clara de lo correcto'],
    challenges: ['Autocrítica excesiva', 'Dificultad para relajarse', 'Juicio hacia los demás', 'Frustración por la imperfección'],
    cita: '"La perfección no es un destino, es una ilusión que nos impide ver nuestra propia humanidad."',
    center: 'Instintivo',
    coreFear: 'Ser malo/a, defectuoso/a o corrupto/a',
    coreDesire: 'Ser bueno/a, íntegro/a y equilibrado/a',
    growth: 7,
    stress: 4,
  },
  {
    id: 2,
    emoji: '🤗',
    title: 'El Ayudador',
    name: 'El Servicial',
    desc: 'Cálido, generoso y atento a las necesidades de los demás. Encuentra su valor siendo indispensable para otros y teme no ser amado o necesitado. Su don es el altruismo genuino cuando reconoce sus propias necesidades.',
    strengths: ['Empatía profunda', 'Generosidad sincera', 'Capacidad de conectar', 'Apoyo incondicional'],
    challenges: ['Descuido de sí mismo', 'Dificultad para pedir ayuda', 'Necesidad de aprobación', 'Orgullo encubierto'],
    cita: '"Cuidar de otros sin cuidar de ti no es amor, es abandono disfrazado de servicio."',
    center: 'Emocional',
    coreFear: 'No ser amado/a o no ser deseado/a',
    coreDesire: 'Sentirse amado/a y apreciado/a',
    growth: 4,
    stress: 8,
  },
  {
    id: 3,
    emoji: '🏆',
    title: 'El Triunfador',
    name: 'El Realizador',
    desc: 'Ambicioso, eficiente y orientado al logro. Se identifica con sus metas y teme el fracaso o no ser valioso. Su don es la inspiración y el liderazgo auténtico cuando se desconecta de la imagen y se conecta con su esencia.',
    strengths: ['Determinación y enfoque', 'Capacidad de inspirar', 'Adaptabilidad', 'Excelencia en lo que hace'],
    challenges: ['Identificación con la imagen', 'Temor al fracaso', 'Competitividad excesiva', 'Desconexión emocional'],
    cita: '"Tu valor no está en lo que logras, sino en quien eres cuando nadie está mirando."',
    center: 'Emocional',
    coreFear: 'No tener valor, ser insignificante',
    coreDesire: 'Sentirse valioso/a y digno/a',
    growth: 6,
    stress: 9,
  },
  {
    id: 4,
    emoji: '🎭',
    title: 'El Romántico',
    name: 'El Individualista',
    desc: 'Creativo, sensible y en busca de identidad y significado. Siente que algo fundamental le falta y teme no ser especial o ser defectuoso. Su don es la autenticidad y la profundidad emocional cuando acepta su ordinaria humanidad.',
    strengths: ['Creatividad única', 'Sensibilidad artística', 'Profundidad emocional', 'Autenticidad'],
    challenges: ['Melancolía recurrente', 'Comparación constante', 'Sentimiento de carencia', 'Dramatización'],
    cita: '"No eres tus emociones. Eres el océano que las sostiene, no la ola que te arrastra."',
    center: 'Emocional',
    coreFear: 'No tener identidad o ser defectuoso/a',
    coreDesire: 'Ser único/a y auténtico/a',
    growth: 1,
    stress: 2,
  },
  {
    id: 5,
    emoji: '🔍',
    title: 'El Observador',
    name: 'El Investigador',
    desc: 'Analítico, perceptivo y en busca de conocimiento. Tiende a retirarse para comprender el mundo y teme ser invadido o no saber suficiente. Su don es la sabiduría objetiva y la claridad mental cuando se abre a la experiencia directa.',
    strengths: ['Pensamiento analítico', 'Autosuficiencia', 'Visión objetiva', 'Capacidad de síntesis'],
    challenges: ['Aislamiento social', 'Dificultad para conectar emocionalmente', 'Acumulación de conocimiento sin acción', 'Desapego excesivo'],
    cita: '"El conocimiento sin acción no es sabiduría, es una biblioteca que nunca se abre."',
    center: 'Mental',
    coreFear: 'Ser inútil, incompetente o invadido/a',
    coreDesire: 'Ser competente y tener conocimiento',
    growth: 8,
    stress: 7,
  },
  {
    id: 6,
    emoji: '🛡️',
    title: 'El Leal',
    name: 'El Leal Escéptico',
    desc: 'Leal, responsable y en busca de seguridad. Su mente está siempre alerta a posibles peligros y teme la incertidumbre o no tener apoyo. Su don es el coraje y la lealtad inquebrantable cuando confía en sí mismo y en el mundo.',
    strengths: ['Lealtad profunda', 'Responsabilidad', 'Pensamiento preventivo', 'Perseverancia'],
    challenges: ['Ansiedad anticipatoria', 'Duda constante', 'Proyección de miedos', 'Dependencia de autoridad'],
    cita: '"El coraje no es la ausencia de miedo, es la decisión de seguir adelante a pesar de él."',
    center: 'Mental',
    coreFear: 'Estar sin apoyo o sin seguridad',
    coreDesire: 'Sentirse seguro/a y respaldado/a',
    growth: 9,
    stress: 3,
  },
  {
    id: 7,
    emoji: '🎉',
    title: 'El Entusiasta',
    name: 'El Entusiasta',
    desc: 'Espontáneo, versátil y amante de la novedad. Busca experiencias placenteras y teme el dolor, el aburrimiento o sentirse limitado. Su don es la alegría auténtica y la visión de posibilidades cuando aprende a estar presente con el dolor.',
    strengths: ['Optimismo contagioso', 'Creatividad e innovación', 'Versatilidad', 'Capacidad de inspirar alegría'],
    challenges: ['Evitación del dolor', 'Dispersión', 'Compromisos superficiales', 'Insatisfacción constante'],
    cita: '"La verdadera libertad no está en escapar del dolor, sino en atravesarlo sin perder la sonrisa."',
    center: 'Mental',
    coreFear: 'Sentir dolor, ser limitado/a o aburrido/a',
    coreDesire: 'Ser feliz y estar satisfecho/a',
    growth: 5,
    stress: 1,
  },
  {
    id: 8,
    emoji: '🦁',
    title: 'El Desafiador',
    name: 'El Protector',
    desc: 'Fuerte, decidido y protector. Busca el control de su entorno y teme la vulnerabilidad o ser traicionado. Su don es el liderazgo justo y la protección de los débiles cuando usa su poder con conciencia y compasión.',
    strengths: ['Determinación férrea', 'Protección de los demás', 'Honestidad directa', 'Capacidad de liderazgo'],
    challenges: ['Intensidad excesiva', 'Dificultad para mostrar vulnerabilidad', 'Control dominante', 'Confrontación innecesaria'],
    cita: '"La verdadera fuerza no está en dominar a otros, sino en tener el valor de ser vulnerable."',
    center: 'Instintivo',
    coreFear: 'Ser vulnerable, controlado/a o traicionado/a',
    coreDesire: 'Protegerse a sí mismo/a y controlar su vida',
    growth: 2,
    stress: 5,
  },
  {
    id: 9,
    emoji: '☮️',
    title: 'El Pacificador',
    name: 'El Pacificador',
    desc: 'Tranquilo, receptivo y en busca de armonía. Tiende a fusionarse con los demás y evita el conflicto. Teme la separación o la pérdida de paz. Su don es la presencia serena y la capacidad de unir cuando despierta a su propia identidad.',
    strengths: ['Capacidad de mediación', 'Empatía y receptividad', 'Visión integradora', 'Paz interior'],
    challenges: ['Evitación del conflicto', 'Fusión con los demás', 'Pasividad', 'Desconexión de sus necesidades'],
    cita: '"La paz no es la ausencia de conflicto, es la capacidad de mantener tu centro en medio de la tormenta."',
    center: 'Instintivo',
    coreFear: 'Perder la conexión o la paz',
    coreDesire: 'Tener paz interior y estabilidad',
    growth: 3,
    stress: 6,
  },
]

export const fadeUp = {
  initial: { opacity: 0, y: 30 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true },
  transition: { duration: 0.5, ease: [0.2, 0, 0, 1] },
}

export const slideVariants = {
  initial: { opacity: 0, x: 40 },
  animate: { opacity: 1, x: 0 },
  exit: { opacity: 0, x: -40 },
}
