// Datos neurológicos completos — fuente: neuroatlas (DrVegetaa)
// Información de regiones cerebrales, funciones, notas clínicas y trastornos

export interface BrainRegion {
  id: string
  name: string
  hierarchy: string
  description: string
  function: string
  clinicalNote: string
  color: string
}

export const BRAIN_REGIONS_DATA: BrainRegion[] = [
  {
    id: 'precentral_gyrus',
    name: 'Precentral gyrus',
    hierarchy: '"Prosencephalon", "Telencephalon", "Frontal lobe"',
    description: 'Primary motor cortex — sends voluntary movement commands to muscles throughout the body. Its neurons form the corticospinal tract, whose axons descend all the way to spinal motor neurons, making it th',
    function: 'Voluntary movement control',
    clinicalNote: 'Stroke or lesion causes contralateral hemiplegia; the upper limb and face are most severely affected due to their large cortical representation.',
    color: '#4A7B9D',
  },
  {
    id: 'superior_frontal_gyrus',
    name: 'Superior frontal gyrus',
    hierarchy: '"Prosencephalon", "Telencephalon", "Frontal lobe"',
    description: 'Involved in working memory, self-awareness, and sustained attention control. It is a key hub of the default mode network, becoming active during self-referential thinking and mind-wandering.',
    function: 'Working memory & self-awareness',
    clinicalNote: 'Damage impairs executive function and sustained attention; reduced grey matter volume is consistently found in schizophrenia and some mood disorders.',
    color: '#4A7B9D',
  },
  {
    id: 'middle_frontal_gyrus',
    name: 'Middle frontal gyrus',
    hierarchy: '"Prosencephalon", "Telencephalon", "Frontal lobe"',
    description: 'Contributes to working memory, decision-making, and language formulation. It plays a central role in cognitive control — the ability to hold goals in mind while filtering out distractions.',
    function: 'Decision-making & cognitive flexibility',
    clinicalNote: 'Lesion disrupts planning, response inhibition, and verbal fluency; patients struggle to adapt when situations or rules change unexpectedly.',
    color: '#4A7B9D',
  },
  {
    id: 'inferior_frontal_gyrus',
    name: 'Inferior frontal gyrus',
    hierarchy: '"Prosencephalon", "Telencephalon", "Frontal lobe"',
    description: 'Contains Broca\'s area in the left hemisphere, which is essential for planning and producing fluent speech. It also contributes to syntactic processing and inhibitory control across both hemispheres.',
    function: 'Speech production (Broca\'s area)',
    clinicalNote: 'Left hemisphere lesion causes Broca\'s aphasia: halting, effortful speech with relatively intact comprehension, often accompanied by frustration.',
    color: '#4A7B9D',
  },
  {
    id: 'cingulate_gyrus',
    name: 'Cingulate gyrus',
    hierarchy: '"Prosencephalon", "Telencephalon", "Limbic lobe"',
    description: 'Links emotion and cognition, and is critical for detecting errors, resolving conflict, and directing attention. The anterior cingulate is particularly important for motivation and pain modulation, whi',
    function: 'Error detection & emotional regulation',
    clinicalNote: 'Anterior cingulate hyperactivity is implicated in OCD and depression; subgenual area 25 is a deep-brain stimulation target for treatment-resistant depression.',
    color: '#6BA3A0',
  },
  {
    id: 'postcentral_gyrus',
    name: 'Postcentral gyrus',
    hierarchy: '"Prosencephalon", "Telencephalon", "Parietal lobe"',
    description: 'Primary somatosensory cortex — receives and maps touch, pressure, pain, and proprioceptive signals from the contralateral body. The body is represented as a somatotopic \'homunculus\', with the hands an',
    function: 'Touch, pressure & pain perception',
    clinicalNote: 'Lesion causes contralateral loss of discriminative touch and proprioception (astereognosis, loss of two-point discrimination) while crude pain and temperature are partially preserved.',
    color: '#4A7B9D',
  },
  {
    id: 'superior_parietal_lobule',
    name: 'Superior parietal lobule',
    hierarchy: '"Prosencephalon", "Telencephalon", "Parietal lobe"',
    description: 'Integrates spatial information from multiple senses and guides visually directed hand movements. It is a core component of the dorsal \'where and how\' visual stream, translating spatial perception into',
    function: 'Spatial integration & visuomotor guidance',
    clinicalNote: 'Lesion produces optic ataxia — the patient cannot reach accurately for objects under visual guidance despite normal strength and vision.',
    color: '#8B6F9E',
  },
  {
    id: 'supramarginal_gyrus',
    name: 'Supramarginal gyrus',
    hierarchy: '"Prosencephalon", "Telencephalon", "Parietal lobe"',
    description: 'Processes phonological information linking sounds to meaning, and contributes to empathic accuracy. It sits at the junction of the temporal and parietal lobes and forms part of the arcuate fasciculus ',
    function: 'Phonological processing & empathy',
    clinicalNote: 'Left hemisphere lesion produces conduction aphasia; right hemisphere lesion reduces the ability to modulate self-centred emotions and understand others\' perspectives.',
    color: '#4A7B9D',
  },
  {
    id: 'angular_gyrus',
    name: 'Angular gyrus',
    hierarchy: '"Prosencephalon", "Telencephalon", "Parietal lobe"',
    description: 'Integrates language, number processing, and spatial cognition at the junction of three lobes. It acts as a multimodal convergence zone, binding auditory, visual, and spatial information to support rea',
    function: 'Reading, arithmetic & language integration',
    clinicalNote: 'Left lesion → Gerstmann syndrome: the classic tetrad of finger agnosia, acalculia, agraphia, and left-right disorientation, all without gross language impairment.',
    color: '#4A7B9D',
  },
  {
    id: 'precuneus',
    name: 'Precuneus',
    hierarchy: '"Prosencephalon", "Telencephalon", "Parietal lobe"',
    description: 'Supports episodic memory retrieval, self-reflection, and conscious awareness. It is one of the most metabolically active cortical regions at rest and is a key hub of the default mode network, deactiva',
    function: 'Episodic memory & self-reflection',
    clinicalNote: 'One of the earliest regions to accumulate amyloid-beta plaques in Alzheimer\'s disease, often years before any clinical symptoms appear.',
    color: '#4A7B9D',
  },
  {
    id: 'superior_temporal_gyrus',
    name: 'Superior temporal gyrus',
    hierarchy: '"Prosencephalon", "Telencephalon", "Temporal lobe"',
    description: 'Contains Wernicke\'s area in the left hemisphere, critical for understanding spoken and written language. The posterior superior temporal sulcus also processes biological motion and voice recognition, ',
    function: 'Language comprehension (Wernicke\'s area)',
    clinicalNote: 'Left lesion produces Wernicke\'s aphasia: fluent but meaningless speech (\'word salad\') with severely impaired comprehension; the patient is often unaware of their errors.',
    color: '#C49A6C',
  },
  {
    id: 'middle_temporal_gyrus',
    name: 'Middle temporal gyrus',
    hierarchy: '"Prosencephalon", "Telencephalon", "Temporal lobe"',
    description: 'Involved in semantic memory retrieval and recognition of faces and objects. It stores conceptual knowledge about the world — meanings of words, properties of objects — making it the brain\'s \'semantic ',
    function: 'Semantic memory & object recognition',
    clinicalNote: 'Degeneration of the anterior middle temporal gyrus erodes conceptual knowledge (\'semantic dementia\'), while posterior lesions can impair face and object recognition.',
    color: '#C49A6C',
  },
  {
    id: 'inferior_temporal_gyrus',
    name: 'Inferior temporal gyrus',
    hierarchy: '"Prosencephalon", "Telencephalon", "Temporal lobe"',
    description: 'Processes complex visual patterns and is critical for recognising objects, faces, and scenes regardless of viewing angle or size. It represents the endpoint of the ventral \'what\' visual stream flowing',
    function: 'Complex visual pattern recognition',
    clinicalNote: 'Bilateral damage to the fusiform face area within this region produces prosopagnosia — the inability to recognise familiar faces, including one\'s own in a mirror.',
    color: '#C49A6C',
  },
  {
    id: 'transverse_temporal_gyrus',
    name: 'Transverse temporal gyrus',
    hierarchy: '"Prosencephalon", "Telencephalon", "Temporal lobe"',
    description: 'Primary auditory cortex (Heschl\'s gyri) — the first cortical region to receive and process sound from the thalamus. It performs initial frequency and temporal analysis, and is organised tonotopically ',
    function: 'Primary sound processing',
    clinicalNote: 'Bilateral lesion causes cortical deafness; unilateral lesion causes subtle deficits in temporal and spectral sound analysis but is masked by the intact contralateral hemisphere.',
    color: '#C49A6C',
  },
  {
    id: 'lingual_gyrus',
    name: 'Lingual gyrus',
    hierarchy: '"Prosencephalon", "Telencephalon", "Occipital lobe"',
    description: 'Processes visual word forms and fundamental visual features including colour. It houses colour area V4 and the visual word form area, and is also thought to contribute to emotional memory and dream im',
    function: 'Visual word recognition & colour processing',
    clinicalNote: 'Lesion causes alexia without agraphia — the patient can write normally but cannot read what they just wrote — and may cause complete loss of colour vision (achromatopsia).',
    color: '#4A7B9D',
  },
  {
    id: 'cuneus',
    name: 'Cuneus',
    hierarchy: '"Prosencephalon", "Telencephalon", "Occipital lobe"',
    description: 'Processes basic visual information from the inferior portion of the contralateral visual field. It contains part of the primary visual cortex (V1) and is important for early-stage analysis of visual c',
    function: 'Lower visual field processing',
    clinicalNote: 'Lesion produces a superior homonymous quadrantanopia — the patient loses the upper portion of the contralateral visual field, which corresponds to the lower retina processed by the cuneus.',
    color: '#4A7B9D',
  },
  {
    id: 'lateral_occipital_cortex',
    name: 'Lateral occipital cortex',
    hierarchy: '"Prosencephalon", "Telencephalon", "Occipital lobe"',
    description: 'Recognises objects and shapes independent of size, viewpoint, or illumination. It represents a mid-stage of the ventral visual stream, combining low-level features into coherent object representations',
    function: 'Object & shape recognition',
    clinicalNote: 'Damage causes visual object agnosia — the patient can draw or describe objects accurately but cannot identify them, illustrating a failure of perception-to-recognition.',
    color: '#A06060',
  },
  {
    id: 'cerebellum',
    name: 'Cerebellum',
    hierarchy: '"Rhombencephalon", "Metencephalon"',
    description: 'Coordinates movement, balance, and fine-tunes motor learning by comparing intended versus actual movements. Though it constitutes only 10% of brain volume, it contains over half of all brain neurons, ',
    function: 'Movement coordination & balance',
    clinicalNote: 'Lesion causes ipsilateral ataxia, dysmetria, intention tremor, dysdiadochokinesia, and nystagmus — remembered by the mnemonic DANISH (Dysdiadochokinesia, Ataxia, Nystagmus, Intention tremor, Slurred s',
    color: '#4A7B9D',
  },
  {
    id: 'midbrain',
    name: 'Midbrain',
    hierarchy: '"Mesencephalon"',
    description: 'Relays motor and sensory signals between the cerebrum and lower brain, and controls eye movement and auditory reflexes. It houses the substantia nigra, the brain\'s primary source of dopamine, whose de',
    function: 'Eye movement control & dopamine production',
    clinicalNote: 'Substantia nigra degeneration causes Parkinson\'s disease; dorsal midbrain compression produces Parinaud syndrome (upgaze palsy, convergence nystagmus) from pineal or tectal lesions.',
    color: '#4A7B9D',
  },
  {
    id: 'pons',
    name: 'Pons',
    hierarchy: '"Rhombencephalon", "Metencephalon"',
    description: 'Bridges the cortex and cerebellum, and contains nuclei regulating sleep, respiration, facial sensation, and eye movement. Its name means \'bridge\' in Latin, reflecting its role as a relay between highe',
    function: 'Sleep regulation & facial sensation relay',
    clinicalNote: 'Rapid osmotic correction of severe hyponatraemia causes central pontine myelinolysis; ventral pontine haemorrhage causes locked-in syndrome — awake but completely paralysed.',
    color: '#4A7B9D',
  },
  {
    id: 'medulla_oblongata',
    name: 'Medulla oblongata',
    hierarchy: '"Rhombencephalon", "Myelencephalon"',
    description: 'Controls the most fundamental autonomic functions: heart rate, blood pressure, breathing, and swallowing. It is also where the major motor and sensory tracts cross from one side of the body to the oth',
    function: 'Heart rate, breathing & swallowing',
    clinicalNote: 'Lateral medullary (Wallenberg) syndrome from posterior inferior cerebellar artery occlusion causes ipsilateral facial sensory loss, dysphagia, and Horner\'s syndrome, plus contralateral body pain and t',
    color: '#4A7B9D',
  },
  {
    id: 'thalamus',
    name: 'Thalamus',
    hierarchy: '"Prosencephalon", "Diencephalon"',
    description: 'Central relay station that routes virtually all sensory and motor signals to the cortex. Almost no sensory information reaches the cortex without first being processed by a specific thalamic nucleus, ',
    function: 'Sensory & motor signal relay hub',
    clinicalNote: 'Thalamic stroke causes sudden dense contralateral hemisensory loss; months later this may transform into severe burning thalamic pain syndrome (Dejerine-Roussy syndrome).',
    color: '#4A7B9D',
  },
  {
    id: 'hypothalamus',
    name: 'Hypothalamus',
    hierarchy: '"Prosencephalon", "Diencephalon"',
    description: 'Master regulator of the body\'s internal environment, controlling hormone release, hunger, thirst, body temperature, and the sleep-wake cycle through its intimate connection with the pituitary gland. D',
    function: 'Hormonal control & homeostasis',
    clinicalNote: 'Lesion can cause diabetes insipidus (ADH deficiency), hypothalamic obesity, or Kallmann syndrome; tumours here (craniopharyngiomas) are notorious for producing complex endocrine and visual deficits.',
    color: '#4A7B9D',
  },
  {
    id: 'hippocampus',
    name: 'Hippocampus',
    hierarchy: '"Prosencephalon", "Telencephalon", "Limbic system"',
    description: 'Essential for converting short-term experiences into lasting long-term memories and for spatial navigation via its \'place cells\'. It is one of the few brain regions that generates new neurons througho',
    function: 'New memory formation & spatial navigation',
    clinicalNote: 'The first structure destroyed in Alzheimer\'s disease — hippocampal atrophy is the earliest structural MRI sign; bilateral surgical removal (the famous H.M. case) produced permanent inability to form a',
    color: '#4A7B9D',
  },
  {
    id: 'amygdala',
    name: 'Amygdala',
    hierarchy: '"Prosencephalon", "Telencephalon", "Limbic system"',
    description: 'Processes fear, emotional memories, and threat responses, and modulates how strongly emotional events are stored in memory. It receives input from all sensory systems and can trigger the fight-or-flig',
    function: 'Fear processing & emotional memory',
    clinicalNote: 'Hyperactive amygdala underlies anxiety disorders and PTSD; bilateral destruction causes Klüver-Bucy syndrome — complete fearlessness and hypersexuality — most commonly seen after herpes simplex enceph',
    color: '#4A7B9D',
  },
  {
    id: 'caudate_nucleus',
    name: 'Caudate nucleus',
    hierarchy: '"Prosencephalon", "Telencephalon", "Basal ganglia"',
    description: 'Part of the dorsal striatum, the caudate nucleus drives goal-directed behaviour and habit formation by reinforcing actions that lead to rewards. It receives dense dopaminergic input from the midbrain ',
    function: 'Goal-directed learning & habit formation',
    clinicalNote: 'Striatal atrophy on MRI (loss of the normal caudate bulge) is a radiological hallmark of Huntington\'s disease; caudate hyperactivity is a consistent finding in OCD neuroimaging.',
    color: '#4A7B9D',
  },
  {
    id: 'putamen',
    name: 'Putamen',
    hierarchy: '"Prosencephalon", "Telencephalon", "Basal ganglia"',
    description: 'Regulates the speed and fluency of movement and is the primary site of motor skill learning within the basal ganglia. Together with the caudate nucleus it forms the striatum, which receives direct dop',
    function: 'Motor skill learning & movement regulation',
    clinicalNote: 'Dopaminergic deafferentation of the putamen from substantia nigra degeneration is the primary cause of Parkinson\'s disease bradykinesia and rigidity.',
    color: '#4A7B9D',
  },
  {
    id: 'globus_pallidus',
    name: 'Globus pallidus',
    hierarchy: '"Prosencephalon", "Telencephalon", "Basal ganglia"',
    description: 'The main output nucleus of the basal ganglia, modulating motor activity by sending inhibitory signals to the thalamus. The internal segment (GPi) is the primary inhibitory gate, while the external seg',
    function: 'Basal ganglia motor output gate',
    clinicalNote: 'The internal globus pallidus (GPi) is one of the primary deep-brain stimulation (DBS) targets for both Parkinson\'s disease and generalised dystonia.',
    color: '#4A7B9D',
  },
  {
    id: 'corpus_callosum',
    name: 'Corpus callosum',
    hierarchy: '"Prosencephalon", "Telencephalon"',
    description: 'The largest white-matter tract in the brain, containing over 200 million axons connecting corresponding regions of the left and right cerebral hemispheres. It allows the two halves of the brain to sha',
    function: 'Interhemispheric communication',
    clinicalNote: 'Surgical section (callosotomy) for severe epilepsy creates a \'split brain\' in which each hemisphere functions independently; congenital agenesis is found in various neurodevelopmental syndromes.',
    color: '#4A7B9D',
  },
  {
    id: 'fornix',
    name: 'Fornix',
    hierarchy: '"Prosencephalon", "Telencephalon", "Limbic system"',
    description: 'C-shaped white-matter arc that carries signals from the hippocampus to the mammillary bodies and hypothalamus, forming the main output pathway of the hippocampal formation. It is a critical node of th',
    function: 'Hippocampo-hypothalamic memory relay',
    clinicalNote: 'Bilateral fornix damage — from tumour, infarct, or surgical injury — causes severe anterograde amnesia with relatively intact intelligence and personality.',
    color: '#4A7B9D',
  },
  {
    id: 'red_nucleus',
    name: 'Red nucleus',
    hierarchy: '"Mesencephalon"',
    description: 'Midbrain structure that coordinates limb movements via the rubrospinal tract, serving as an alternative motor pathway when the corticospinal tract is damaged. Its pink colour in fresh brain tissue is ',
    function: 'Limb movement coordination',
    clinicalNote: 'Lesion combining with nearby CN III produces Claude\'s syndrome: ipsilateral oculomotor palsy (ptosis, mydriasis) with contralateral limb ataxia from rubral pathway damage.',
    color: '#4A7B9D',
  },
]
